site_name: logx-reader
site_url: https://clu-ling.github.io/logx-reader
site_description: Project documentation with Markdown.
site_author: Gus Hahn-Powell

repo_url: https://github.com/clu-ling/logx-reader/
edit_uri: "blob/master/docs/"

theme:
  name: readthedocs
  highlightjs: true
  hljs_style: github
  # list additional languages here
  hljs_languages:
    - yaml
    - scala
  analytics:
    gtag: null
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  nav_style: dark
  locale: en

nav:
    # NOTE: all relative to docs/
    - Home: index.md
    - User Guide:
        - Installation: install.md
        - Usage: tutorial.md
    - Development:
        - Install: dev/install.md
        - Documentation: dev/documentation.md
        - Developing: dev/developing.md
        - Testing: dev/test.md
        - Annotations: dev/annotations.md
        - How it Works: dev/howitworks.md
        - FAQ: dev/faq.md
    - API Documentation:
        - "core": api/core/index.html
        - "reader": api/reader/index.html
        - "rest": api/rest/index.html
    - Contributors: authors.md

extra_css:
    - css/extra.css

# footnotes
# pymdownx.emoji
# pymdownx.caret
# pymdownx.mark
# pymdownx.tilde
# pymdownx.details
# pymdownx.superfences
# pymdownx.tabbed
markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
    # - mdx_gh_links:
    #     user: clu-ling
    #     repo: clu-phontools

copyright: Copyright &copy; 2021 <a href="https://parsertongue.org/about">Gus Hahn-Powell</a>.
#copyright: Copyright &copy; 2021 <a href="https://parsertongue.org/about">Gus Hahn-Powell</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">CLU-LING Team</a>.

plugins:
    - search
    # - redirects:
    #     redirect_maps:
    #         user-guide/plugins.md: dev-guide/plugins.md
    #         user-guide/custom-themes.md: dev-guide/themes.md
    #         user-guide/styling-your-docs.md: user-guide/choosing-your-theme.md

    # # # see https://github.com/daizutabi/mkapi/
    # - mkapi
    # # see https://github.com/mercari/mkdocs-git-snippet
    - git-snippet
    # see https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
    - git-revision-date-localized
    # see https://github.com/timvink/mkdocs-git-authors-plugin
    - git-authors
    # see https://github.com/fralau/mkdocs-mermaid2-plugin
    - mermaid2
    # TODO: add https://github.com/timvink/mkdocs-table-reader-plugin
    # TODO: add https://github.com/fralau/mkdocs-mermaid2-plugin