openapi: 3.0.0
info:
  version: "1.0.0"
  title: LogX reader API
  description: RESTful API exposing core functionality of LogX reader.
  contact:
    email: gus@parsertongue.org
# https://swagger.io/docs/specification/api-host-and-base-path/
servers:
 #- url: "http://localhost:9000/api"
 - url: /api
tags:
  - name: "ie"
    description: |
      Operations related to information extraction.
  - name: "config"
    description: |
      Endpoints for inspecting project config.
paths:
  /extract:
    get:
      tags:
        - ie
      summary: |
        Extract Odin Mentions from text.
      description: |
        Extract Odin Mentions from text.
      parameters:
        - name: text
          in: query
          description: |
            The text to be analyzed.
          required: true
          schema:
            type: string
        #  example:
      responses:
        '200':
          description: Array of Mentions matching the criteria.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MentionData'

  /annotate:
    get:
      tags:
        - ie
      summary: |
        Annotate text.
      description: |
        Annotate (tokenize, tag, parse, etc.) text.
      parameters:
        - name: text
          in: query
          description: |
            The text to be annotated.
          required: true
          schema:
            type: string
        #  example:
      responses:
        '200':
          description: Annotated text in the form of Document JSON.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'

  # /buildinfo:
  #   get:
  #     tags:
  #       - config
  #     summary: |
  #       App version information
  #     description: |
  #       Display information about the app's commit, branch, etc.
  #     responses:
  #       '200':
  #         description: Version information
  #         content:
  #           application/json

  # /config:
  #   get:
  #     tags:
  #       - config
  #     summary: |
  #       Appplication config
  #     description: |
  #       Display app configuration for debugging purposes
  #     responses:
  #       '200':
  #         description: Config information
  #         content:
  #           application/json
            
components:
  schemas:

    Document:
      type: object
      required:
        - id
        - text
        - sentences
      properties:
        id:
          type: integer
          format: int64
          description: |
            The equivalence hash for this org.clulab.processors.Document.
        text:
          type: string
          description: |
            The original text from which this Document was produced.
        sentences:
          type: array
          description: |
            array of org.clulab.processors.Sentence.
          items:
            $ref: '#/components/schemas/Sentence'

    Sentence:
      type: object
      required:
        - words
        - startOffsets
        - endOffsets
  #      - raw
  #      - tags
  #      - lemmas
  #      - entities
  #      - norms
  #      - chunks
        - graphs
      properties:
        words:
          type: array
          description: |
            The tokens for this sentence.
          items:
            type: string
        lemmas:
          type: array
          description: |
            The lemma form of each token in this sentence.
          items:
            type: string
        tags:
          type: array
          description: |
            The part of speech tag for each token in this sentence.
          items:
            type: string
        chunks:
          type: array
          description: |
            The BIO-style chunk label designating a coarse XP assignment for each token in this sentence.
          items:
            type: string
        entities:
          type: array
          description: |
            The BIO-style entity label for each token in this sentence.
          items:
            type: string
        startOffsets:
          type: array
          description: |
            The character-based start offset for each token in this sentence.
          items:
            type: integer
            format: int32
        endOffsets:
          type: array
          description: |
            The character-based end offset for each token in this sentence.
          items:
            type: integer
            format: int32
        graphs:
          $ref: "#/components/schemas/GraphMap"

    GraphMap:
      type: object
      description: |
        Map of graph name -> DirectedGraph.
      additionalProperties:
        type: string
        description: |
          The name of a DirectedGraph.

    DirectedGraph:
      type: object
      properties:
        edges:
          type: array
          description: |
            A edges comprising this graph.
          items:
            $ref: '#/components/schemas/Edge'
        roots:
          type: array
          description: |
            The token indices corresponding to the root nodes for this DirectedGraph.
          items:
            type: integer
            format: int32

    Edge:
      type: object
      required:
        - source
        - destination
        - relation
      properties:
        source:
          type: integer
          format: int32
          description: |
            The token index for the source vertex.
        destination:
          type: integer
          format: int32
          description: |
            The token index for the destination vertex.
        relation:
          type: string
          description: |
            The relation to which this Edge corresponds.
    Interval:
      type: object
      required:
        - start
        - end
      properties:
        start:
          type: integer
          format: int32
          description: |
            Inclusive start of org.clulab.struc.Interval.
        end:
          type: integer
          format: int32
          description: |
            Exclusive end of org.clulab.struct.Interval.

    MentionData:
      type: object
      required:
        - documents
        - mentions
      properties:
        documents:
          type: object
          description: |
            Map from equivalence hash to org.clulab.processors.Document.
          additionalProperties:
            type: integer
            format: int64
        mentions:
          type: array
          description: |
            array of org.clulab.odin.Mention.
          items:
            $ref: '#/components/schemas/Mention'

    Mention:
      type: object
      required:
        - type
        - id
        - text
        - labels
        - tokenInterval
        - characterStartOffset
        - characterEndOffset
        - sentence
        - document
        - keep
        - foundBy

      properties:
        type:
          type: array
          description: |
            A code denoting the type of this mention.
          items:
            enum: ["TextBoundMention", "EventMention", "RelationMention", "CrossSentenceMention"]
        id:
          type: string
          description: |
            Equivalence identifier of the form `shortCode:equivalenceHash`.  `shortCode` is expected to be one of the following: ["T", "E", "R", "CS"].
        text:
          type: string
          description: |
            Enclosing text span corresponding to this Mention.
        labels:
          type: array
          description: |
            The labels for this Mention.
          items:
            type: string
        tokenInterval:
          $ref: "#/components/schemas/Interval"
        characterStartOffset:
          type: integer
          format: int32
        characterEndOffset:
          type: integer
          format: int32
        sentence:
          type: integer
          format: int32
          description: |
            The sentence index for the org.clulab.processors.Sentence matching the referenced org.clulab.processors.Document.
        document:
          type: integer
          format: int64
          description: |
            The ID corresponding to the document referenced in the `documents` property of `MentionData`.
        keep:
          type: boolean
          description: |
            Whether or not the Mention was intended to be retained.
        foundBy:
          type: string
          description: |
            The name of the rule responsible which produced this Mention.
