name: Scala CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.sha.outputs.sha_short }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: generate short commit hash
      id: sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
    # Setup docker
    - name: Set up QEMUclu-template
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # JDK 11 and tests
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: "11"
        java-package: jdk
    - name: Run tests
      run: sbt cleanTest
    # docs
    - name: "Create documentation (API docs)"
      run: sbt doc
    # Copy api docs to docs/api, see https://github.com/canastro/copy-action
    - name: copy files reader
      uses: canastro/copy-file-action@master
      with:clu-template
        source: "reader/target/scala-2.12/api/."
        target: "docs/api/reader/"
        flags: "-r"
    - name: copy files rest
      uses: canastro/copy-file-action@master
      with:
        source: "rest/target/scala-2.12/api/."
        target: "docs/api/rest/"
        flags: "-r"
    # docs
    - name: "Create documentation (other)"
      env:clu-template
      run: |
        docker pull "${ORG}/${IMAGE_NAME}:${TAG}"
        docker run -i -v "$GITHUB_WORKSPACE:/app" "${ORG}/${IMAGE_NAME}:${TAG}" mkdocs build -c
    - name: Deploy docs
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        # see https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}

      #run: sbt coverage test
    #- name: Coverage Report
    #  run: sbt coverageReport
    #- name: Upload coverage to Codecov
    #  uses: codecov/codecov-action@v1
